title: "Nesios Stuff Addon"
author:
  email: "nesiosdev@outlook.fr"
minima:
 skin: dark
social_links:
    twitter_username: N9SiOs
    github_username: N3siOS
header_pages:
 - about.md
 - download.md
theme: minima
