title: "Nesios Stuff Addon"
author: Nesios
email: "nesiosdev@outlook.fr"
minima:
social_links:
 twitter_username: N9SiOs
 github_username: N3siOS
header_pages:
 - about.md
 - download.md
theme: minima
